Theme switcher
amlcloud/seeder pull request #80
Opened 2022-08-08 11:46 UTC by fuzheng1998

write back to DB when theme change

2022-08-09 10:58 UTC, ThuvaMathu reviewed
Lgtm. Let's see in action.

2022-08-10 01:05 UTC, fuzheng1998 commented
fetching theme from DB works now.  @kovarny

2022-08-10 23:34 UTC, kovarny requested changes

2022-08-10 23:34 UTC, kovarny commented on lib/state/theme_state_notifier.dart
> +          .then((value) {
why chaining if it is just one action to assign the state?

2022-08-10 23:34 UTC, kovarny commented on lib/state/theme_state_notifier.dart
> +            bool isDark = value == 'light' ? false : true;
Don't introduce variables for no reason.

2022-08-10 23:34 UTC, kovarny commented on lib/state/theme_state_notifier.dart
> +  var loginState = ref.watch(isLoggedIn);
Same

2022-08-10 23:34 UTC, kovarny commented on lib/state/theme_state_notifier.dart
> +      var userSettingDoc =
unneeded variable

2022-08-11 04:18 UTC, kovarny approved these changes

2022-08-11 05:42 UTC, merged